Repository autogluon/autogluon, pull requests merged in 2022-07, with the labels that each got.

#1920 Added caching y_pred_proba_val
  core/src/autogluon/core/trainer/abstract_trainer.py
Labels: enhancement, tabular

#1919 Cleanup HPO artifacts
  core/src/autogluon/core/models/abstract/abstract_model.py
  core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
Labels: enhancement, tabular

#1914 Add period inference from freq strings to sktime
  timeseries/setup.py
  timeseries/src/autogluon/timeseries/configs/presets_configs.py
  timeseries/src/autogluon/timeseries/models/presets.py
  timeseries/src/autogluon/timeseries/models/sktime/abstract_sktime.py
  timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
  timeseries/src/autogluon/timeseries/utils/seasonality.py
  timeseries/tests/unittests/common.py
  timeseries/tests/unittests/models/test_sktime.py
Labels: enhancement, module: timeseries

#1973 update v0.5.1 release notes for time series
  docs/whats_new/v0.5.1.md
Labels: module: timeseries

#1985 Linting code in the `timeseries` module with `black` and `isort`
  .github/workflow_scripts/env_setup.sh
  .github/workflow_scripts/lint_check.sh
  docs/build.yml
  pyproject.toml
  timeseries/setup.py
  timeseries/src/autogluon/timeseries/__init__.py
  timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py
  timeseries/src/autogluon/timeseries/evaluator.py
  timeseries/src/autogluon/timeseries/learner.py
  timeseries/src/autogluon/timeseries/models/__init__.py
  timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
  timeseries/src/autogluon/timeseries/models/abstract/model_trial.py
  timeseries/src/autogluon/timeseries/models/ensemble/greedy_ensemble.py
  timeseries/src/autogluon/timeseries/models/gluonts/abstract_gluonts.py
  timeseries/src/autogluon/timeseries/models/gluonts/callback.py
  timeseries/src/autogluon/timeseries/models/gluonts/models.py
  timeseries/src/autogluon/timeseries/models/presets.py
  timeseries/src/autogluon/timeseries/models/sktime/__init__.py
  timeseries/src/autogluon/timeseries/models/sktime/abstract_sktime.py
  timeseries/src/autogluon/timeseries/models/sktime/models.py
  timeseries/src/autogluon/timeseries/predictor.py
  timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
  timeseries/src/autogluon/timeseries/trainer/auto_trainer.py
  timeseries/src/autogluon/timeseries/utils/seasonality.py
  timeseries/tests/test_check_style.py
  timeseries/tests/unittests/common.py
  timeseries/tests/unittests/models/test_es_callback.py
  timeseries/tests/unittests/models/test_gluonts.py
  timeseries/tests/unittests/models/test_models.py
  timeseries/tests/unittests/models/test_sktime.py
  timeseries/tests/unittests/test_evaluator.py
  timeseries/tests/unittests/test_trainer.py
  timeseries/tests/unittests/test_ts_dataset.py
Labels: code cleanup, module: timeseries
