Repository autogluon/autogluon, pull requests merged in 2023-07, with the labels that each got.

#3373 vw version bump
  common/src/autogluon/common/utils/try_import.py
  tabular/setup.py
Labels: module: tabular, dependency

#3379 [AutoMM] Support customizing use_fast for AutoTokenizer
  multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml
  multimodal/src/autogluon/multimodal/data/process_text.py
  multimodal/src/autogluon/multimodal/utils/data.py
  multimodal/tests/hf_model_list.yaml
  multimodal/tests/unittests/others_2/test_data_processors.py
Labels: model list checked

#3384 [AutoMM] Fix the input keys of categorical MLP
  multimodal/src/autogluon/multimodal/models/categorical_mlp.py
  multimodal/tests/unittests/predictor/test_predictor.py
Labels: model list checked

#3388 [Doc] Add AutoMM FAQs
  docs/tutorials/multimodal/multimodal-faq.md
Labels: model list checked

#3355 Refactor path
  common/src/autogluon/common/utils/utils.py
  common/tests/unittests/test_setup_outputdir.py
  core/src/autogluon/core/hpo/executors.py
  core/src/autogluon/core/learner/abstract_learner.py
  core/src/autogluon/core/models/abstract/abstract_model.py
  core/src/autogluon/core/models/abstract/model_trial.py
  core/src/autogluon/core/models/ensemble/bagged_ensemble_model.py
  core/src/autogluon/core/models/ensemble/fold_fitting_strategy.py
  core/src/autogluon/core/models/ensemble/stacker_ensemble_model.py
  core/src/autogluon/core/trainer/abstract_trainer.py
  multimodal/tests/unittests/others/test_save_path.py
  tabular/src/autogluon/tabular/models/catboost/catboost_model.py
  tabular/src/autogluon/tabular/models/fasttext/fasttext_model.py
  tabular/src/autogluon/tabular/models/lgb/lgb_model.py
  tabular/src/autogluon/tabular/models/rf/compilers/native.py
  tabular/src/autogluon/tabular/models/rf/compilers/onnx.py
  tabular/src/autogluon/tabular/models/tab_transformer/tab_transformer_model.py
  tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
  tabular/src/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py
  tabular/src/autogluon/tabular/models/xgboost/xgboost_model.py
  tabular/src/autogluon/tabular/predictor/predictor.py
  tabular/tests/unittests/models/test_dummy.py
  tabular/tests/unittests/test_tabular.py
  timeseries/src/autogluon/timeseries/models/abstract/abstract_timeseries_model.py
  timeseries/src/autogluon/timeseries/models/abstract/model_trial.py
  timeseries/src/autogluon/timeseries/models/autogluon_tabular/mlforecast.py
  timeseries/src/autogluon/timeseries/models/gluonts/torch/models.py
  timeseries/src/autogluon/timeseries/models/multi_window/multi_window_model.py
  timeseries/src/autogluon/timeseries/predictor.py
  timeseries/src/autogluon/timeseries/trainer/abstract_trainer.py
  timeseries/tests/conftest.py
  timeseries/tests/unittests/models/test_models.py
  timeseries/tests/unittests/test_learner.py
  timeseries/tests/unittests/test_trainer.py
Labels: enhancement, model list checked, priority: 0

#3397 [FIX] fix detection tutorial index
  docs/tutorials/multimodal/index.md
  docs/tutorials/multimodal/object_detection/index.md
Labels: model list checked

#3399 [AutoMM] Add unit tests for trimming sequence lengths
  multimodal/src/autogluon/multimodal/data/process_text.py
  multimodal/tests/unittests/others/test_utils.py
Labels: model list checked

#3408 Add log for fit time adjustments
  core/src/autogluon/core/models/abstract/abstract_model.py
Labels: API & Doc, module: tabular

#3418 Fix crash when `time_limit` is None and overwritten via `max_time_limit`
  core/src/autogluon/core/models/abstract/abstract_model.py
Labels: bug, module: tabular

#3422 [AutoMM] Upgrade torchmetrics to 1.0
  multimodal/setup.py
  multimodal/src/autogluon/multimodal/optimization/lit_mmdet.py
  multimodal/src/autogluon/multimodal/optimization/utils.py
  multimodal/src/autogluon/multimodal/utils/__init__.py
  multimodal/src/autogluon/multimodal/utils/map.py
  multimodal/src/autogluon/multimodal/utils/object_detection.py
  multimodal/tests/unittests/others/test_metrics.py
Labels: model list checked
