Repository autogluon/autogluon, pull requests merged in 2023-02, with the labels that each got.

#2772 [timeseries] Update documentation for timeseries
  docs/tutorials/timeseries/forecasting-indepth.md
  docs/tutorials/timeseries/forecasting-model-zoo.rst
  timeseries/src/autogluon/timeseries/models/__init__.py
  timeseries/src/autogluon/timeseries/models/local/__init__.py
  timeseries/src/autogluon/timeseries/models/local/statsforecast.py
  timeseries/src/autogluon/timeseries/models/presets.py
  timeseries/tests/unittests/models/test_local.py
Labels: API & Doc, module: timeseries

#2815 Fix torch version range, support 1.13
  tabular/setup.py
Labels: priority: 0

#2794 Fix TIMM integration to support adaptive image size
  multimodal/src/autogluon/multimodal/configs/model/fusion_mlp_image_text_tabular.yaml
  multimodal/src/autogluon/multimodal/data/process_image.py
  multimodal/src/autogluon/multimodal/models/timm_image.py
  multimodal/src/autogluon/multimodal/predictor.py
  multimodal/tests/unittests/others/test_process_image.py
  multimodal/tests/unittests/others_2/test_backward_compatibility.py
  multimodal/tests/unittests/others_2/test_predictor_with_bart.py
Labels: model list checked

#2691 Remove dask and distributed dependencies
  core/setup.py
  docs/requirements_doc.txt
  multimodal/setup.py
Labels: dependency, priority: 0

#2826 [DocClassifier] Change checkpoint of doc classification
  docs/tutorials/multimodal/document/document_classification.md
  multimodal/tests/hf_model_list.yaml
Labels: model list checked

#2818 [Multimodal] Update version bounds
  core/src/autogluon/core/_setup_utils.py
  multimodal/setup.py
  multimodal/src/autogluon/multimodal/data/labelencoder_ner.py
  multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
  multimodal/src/autogluon/multimodal/data/process_document.py
  multimodal/src/autogluon/multimodal/data/process_ner.py
  multimodal/src/autogluon/multimodal/data/process_text.py
Labels: module: multimodal, dependency, priority: 0

#2809 [eda][docs] Tutorials and UX improvements
  .github/workflow_scripts/build_eda_tutorial.sh
  .github/workflows/continuous_integration.yml
  docs/build_pip_install.sh
  docs/index.rst
  docs/tutorials/eda/eda-auto-analyze-interaction.md
  docs/tutorials/eda/eda-auto-covariate-shift.md
  docs/tutorials/eda/eda-auto-dataset-overview.md
  docs/tutorials/eda/eda-auto-quick-fit.md
  docs/tutorials/eda/eda-auto-target-analysis.md
  docs/tutorials/eda/index.rst
  docs/tutorials/index.rst
  eda/src/autogluon/eda/auto/__init__.py
  eda/src/autogluon/eda/auto/simple.py
  eda/src/autogluon/eda/visualization/dataset.py
  eda/src/autogluon/eda/visualization/interaction.py
  eda/src/autogluon/eda/visualization/jupyter.py
  eda/src/autogluon/eda/visualization/missing.py
  eda/src/autogluon/eda/visualization/shift.py
  eda/tests/unittests/auto/test_simple.py
  eda/tests/unittests/visualization/test_interaction.py
  eda/tests/unittests/visualization/test_missing.py
  eda/tests/unittests/visualization/test_model.py
Labels: module: eda

#2842 Fix Tabular multimodal preset
  tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
Labels: bug

#2839 [AutoMM] Support HPO presets
  multimodal/src/autogluon/multimodal/matcher.py
  multimodal/src/autogluon/multimodal/predictor.py
  multimodal/src/autogluon/multimodal/presets.py
  multimodal/src/autogluon/multimodal/utils/__init__.py
  multimodal/src/autogluon/multimodal/utils/config.py
  multimodal/src/autogluon/multimodal/utils/data.py
  multimodal/tests/unittests/others/test_utils.py
  multimodal/tests/unittests/others_2/test_hpo.py
Labels: model list checked

#2857 [Multimodal] Fix eval_metric=spearmanr
  multimodal/src/autogluon/multimodal/data/process_text.py
  multimodal/src/autogluon/multimodal/optimization/lit_module.py
  multimodal/tests/unittests/others_2/test_predictor_regression_eval_metrics.py
Labels: model list checked

#2840 [multimodal] Unifying dump/export model by introducing ExportMixin
  multimodal/src/autogluon/multimodal/predictor.py
  multimodal/src/autogluon/multimodal/utils/__init__.py
  multimodal/src/autogluon/multimodal/utils/export.py
  multimodal/tests/unittests/others/test_deployment_onnx.py
  multimodal/tests/unittests/others/test_deployment_torch.py
Labels: model list checked

#2833 [DocClassifier] add missing documents support and exception handling
  docs/tutorials/multimodal/document/document_classification.md
  multimodal/src/autogluon/multimodal/configs/data/default.yaml
  multimodal/src/autogluon/multimodal/data/infer_types.py
  multimodal/src/autogluon/multimodal/data/process_document.py
  multimodal/src/autogluon/multimodal/utils/checkpoint.py
  multimodal/src/autogluon/multimodal/utils/cloud_io.py
  multimodal/src/autogluon/multimodal/utils/data.py
Labels: model list checked

#2854 [eda] API docs
  docs/tutorials/eda/autogluon.eda.auto.rst
  docs/tutorials/eda/autogluon.eda.base-apis.rst
  docs/tutorials/eda/autogluon.eda.dataset.rst
  docs/tutorials/eda/autogluon.eda.interaction.rst
  docs/tutorials/eda/autogluon.eda.missing.rst
  docs/tutorials/eda/autogluon.eda.model.rst
  docs/tutorials/eda/autogluon.eda.shift.rst
  docs/tutorials/eda/autogluon.eda.transform.rst
  docs/tutorials/eda/eda-auto-covariate-shift.md
  docs/tutorials/eda/eda-auto-dataset-overview.md
  docs/tutorials/eda/eda-auto-quick-fit.md
  docs/tutorials/eda/eda-auto-target-analysis.md
  docs/tutorials/eda/index.rst
  eda/src/autogluon/eda/analysis/base.py
  eda/src/autogluon/eda/analysis/interaction.py
  eda/src/autogluon/eda/analysis/model.py
  eda/src/autogluon/eda/analysis/transform.py
  eda/src/autogluon/eda/visualization/missing.py
Labels: module: eda

#2860 Focal loss
  multimodal/src/autogluon/multimodal/configs/optimization/adamw.yaml
  multimodal/src/autogluon/multimodal/optimization/losses.py
  multimodal/src/autogluon/multimodal/optimization/utils.py
  multimodal/src/autogluon/multimodal/predictor.py
  multimodal/tests/unittests/others/test_classification.py
Labels: model list checked

#2873 [AutoMM] Support prediction with image str or list
  multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py
  multimodal/src/autogluon/multimodal/predictor.py
  multimodal/src/autogluon/multimodal/utils/data.py
  multimodal/tests/unittests/others/test_classification.py
  multimodal/tests/unittests/others_2/test_images.py
  multimodal/tests/unittests/predictor/test_predictor.py
Labels: model list checked

#2858 Update version cap of lightning in timeseries
  timeseries/setup.py
Labels: module: timeseries

#2875 [timeseries] Fix dependency version ranges
  timeseries/setup.py
Labels: module: timeseries

#2877 [timeseries] update sktime dependency range
  timeseries/setup.py
  timeseries/src/autogluon/timeseries/__init__.py
Labels: module: timeseries

#2879 Skip validation
  docs/tutorials/multimodal/advanced_topics/customization.md
  multimodal/src/autogluon/multimodal/configs/optimization/adamw.yaml
  multimodal/src/autogluon/multimodal/optimization/lit_module.py
  multimodal/src/autogluon/multimodal/predictor.py
  multimodal/tests/unittests/others_2/test_predictor_advanced.py
Labels: model list checked

#2890 Tabular: Switch to use multimodal fusion
  tabular/src/autogluon/tabular/configs/hyperparameter_configs.py
  tabular/tests/unittests/models/test_automm.py
Labels: enhancement, module: tabular, module: multimodal

#2891 [Performance]Set persistent_worker in prediction dataloader to False + Remove seed in inference
  multimodal/src/autogluon/multimodal/configs/environment/default.yaml
  multimodal/src/autogluon/multimodal/data/datamodule.py
  multimodal/src/autogluon/multimodal/matcher.py
  multimodal/src/autogluon/multimodal/predictor.py
  multimodal/src/autogluon/multimodal/utils/__init__.py
  multimodal/src/autogluon/multimodal/utils/config.py
  multimodal/src/autogluon/multimodal/utils/inference.py
  multimodal/src/autogluon/multimodal/utils/object_detection.py
  multimodal/tests/unittests/predictor/test_predictor.py
Labels: model list checked

#2889 Add `_add_stream_handler()` call to common init
  common/src/autogluon/common/__init__.py
Labels: bug, API & Doc, priority: 2, module: common

#2900 [docs] Updated cloud tutorials to 0.6 content
  docs/build_doc.sh
  docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-deployment.md
  docs/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-training.md
Labels: API & Doc

#2905 [Tutorial] AutoMM Presets
  docs/tutorials/multimodal/advanced_topics/index.rst
  docs/tutorials/multimodal/advanced_topics/presets.md
  docs/tutorials/multimodal/index.rst
Labels: model list checked

#2867 [multimodal] Add yolox_x config and update presets to use yolox
  docs/tutorials/multimodal/object_detection/finetune/detection_high_performance_finetune_coco.md
  multimodal/src/autogluon/multimodal/configs/pretrain/detection/yolox/yolox_x_8x8_300e_coco.py
  multimodal/src/autogluon/multimodal/models/mmdet_image.py
  multimodal/src/autogluon/multimodal/presets.py
  multimodal/src/autogluon/multimodal/utils/metric.py
  multimodal/tests/hf_model_list.yaml
  multimodal/tests/unittests/others/test_object_detection.py
Labels: model list checked

#2912 Allow no y in leaderboard
  common/src/autogluon/common/loaders/load_s3.py
  tabular/src/autogluon/tabular/learner/abstract_learner.py
  tabular/src/autogluon/tabular/predictor/predictor.py
  tabular/tests/unittests/test_tabular.py
Labels: enhancement, module: tabular, priority: 1

#2910 Adding tutorial and related util functions for detection with dataframe
  docs/tutorials/multimodal/object_detection/data_preparation/object_detection_with_dataframe.md
  multimodal/src/autogluon/multimodal/predictor.py
  multimodal/src/autogluon/multimodal/utils/__init__.py
  multimodal/src/autogluon/multimodal/utils/object_detection.py
  multimodal/tests/unittests/others/test_object_detection.py
Labels: model list checked

#2909 Accelerate FastAI Preprocessing + Fix TabularNN time_limit
  tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py
  tabular/src/autogluon/tabular/models/tabular_nn/torch/tabular_nn_torch.py
Labels: bug, enhancement, module: tabular, priority: 0

#2913 Add refit_full logging
  tabular/src/autogluon/tabular/models/knn/knn_model.py
  tabular/src/autogluon/tabular/predictor/predictor.py
Labels: API & Doc, module: tabular

#2920 Add hyperopt notes
  core/setup.py
Labels: API & Doc

#2899 [Tutorial] Focal loss
  docs/tutorials/multimodal/advanced_topics/focal_loss.md
  docs/tutorials/multimodal/advanced_topics/index.rst
  docs/tutorials/multimodal/index.rst
Labels: model list checked

#2897 [Tutorial] Fewshot FusionSVM predictor
  docs/tutorials/multimodal/advanced_topics/few_shot_learning.md
  docs/tutorials/multimodal/advanced_topics/index.rst
  docs/tutorials/multimodal/index.rst
Labels: model list checked

#2916 [AutoMM] Lazy import ray
  multimodal/src/autogluon/multimodal/presets.py
Labels: feature: hpo, module: multimodal, dependency

#2926 Fixing index.rst file paths for object detection with dataframe
  docs/tutorials/multimodal/index.rst
  docs/tutorials/multimodal/object_detection/data_preparation/index.rst
  docs/tutorials/multimodal/object_detection/index.rst
Labels: model list checked

#2925 Fixing index.rst file paths for Focal Loss and Few Shot SVM
  docs/tutorials/multimodal/advanced_topics/index.rst
  docs/tutorials/multimodal/index.rst
Labels: model list checked

#2923 [tabular] fix compile_models error when onnxruntime is missing
  tabular/setup.py
  tabular/src/autogluon/tabular/models/rf/compilers/onnx.py
Labels: bug, module: tabular, dependency

#2927 [multimodal] [0.7.0] Change num_gpus in detection's presets to -1
  multimodal/src/autogluon/multimodal/presets.py
Labels: bug

#2930 [Tutorial Fixes] Fewshot svm predictor
  docs/tutorials/multimodal/advanced_topics/few_shot_learning.md
Labels: model list checked

#2928 [Tutorial] Add pre-requisite on Tesseract installation
  docs/tutorials/multimodal/document/document_classification.md
  docs/tutorials/multimodal/document/index.rst
  docs/tutorials/multimodal/index.rst
Labels: model list checked

#2936 [multimodal] [tutorial] update quick start tutorial for detection
  docs/tutorials/multimodal/object_detection/finetune/detection_fast_finetune_coco.md
  docs/tutorials/multimodal/object_detection/finetune/detection_high_performance_finetune_coco.md
  docs/tutorials/multimodal/object_detection/quick_start/quick_start_coco.md
  multimodal/tests/hf_model_list.yaml
Labels: model list checked

#2939 [Post 0.7][multimodal] update hf_model_list for clip-vit-large
  multimodal/tests/hf_model_list.yaml
Labels: model list checked

#2946 [Post 0.7][multimodal] remove clip in fusion models
  multimodal/tests/unittests/predictor/test_predictor.py
Labels: model list checked
